language: php

services:
  - mysql

env:
  global:
    - setup=stable
    - APP_ENV=testing
    - APP_DEBUG=false
    - APP_KEY=01234567890123456789012346579012
    - DB_CONNECTION=mysql
    - DB_HOST=localhost
    - DB_DATABASE=barryvanveen
    - DB_USERNAME=root
    - DB_PASSWORD=
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync
    - GTM_CODE=false
    - LINKEDIN_PROFILE="https://www.linkedin.com/in/barryvanveen"
    - GITHUB_PROFILE="https://www.github.com/barryvanveen"
    - COMMENTS_ENABLED=1
    - MAIL_DRIVER=log
    - MAIL_TO_ADDRESS=barryvanveen@gmail.com
    - MAIL_TO_NAME="Barry van Veen"

matrix:
  fast_finish: true
  include:
    - php: 7.0.21
    - php: 7.0.21
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
  allow_failures:
    - php: 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - mysql -e 'create database barryvanveen;'
  - php artisan migrate

script: vendor/bin/phpunit
